### PR TITLE
Add links to the tie breaking algorithm

### PR DESCRIPTION
**Pull request by dandv**
BTW, an FAQ entry "What are Aloglia's text matching features" would be great. It should list typo tolerance etc.

### CODE REVIEW

**Comment by vvo** [comment]
@dandv Thanks a lot for all your detailed contributions to the Algolia faq.

I see you are a meteor.js consultant right now. Do you have some Meteor.js websites that will use/are using Algolia?

Do you think Meteor.js developers have all the needed tools to easily integrate Algolia in their meteor.js apps?

Thanks. 

cc @redox

**Comment by dandv** [comment]
Hi @vvo,

I've just started building [iDoRecall](http://idorecall.com) with Meteor, and plan to use Algolia for a top-notch search experience. The app organizes a user's flashcards, so it's a very personal part of a user's memory, which is why we want to provide a great search experience.

With regards to Meteor integrations with Algolia, there are [three packages](https://atmospherejs.com/?q=algolia) at the moment, each of which could use some improvements. As you [might have seen](https://github.com/acemtp/meteor-algolia/issues/5), acemtp's package is the most promising, and [including algoliasearch.js from a submodule](https://github.com/acemtp/meteor-algolia/issues/6) would make the integration much cleaner and easier to keep up to date with the latest version.

**Comment by vvo** [comment]
Thanks for your insights, answered the corresponding issues.

**Comment by acemtp** [comment]
@vvo: I'm a friend of nicolas and julien and wanted to use algolia for http://fastosphere.meteor.com that's why I created the algolia package :)

**Comment by vvo** [comment]
Great! I hope we can make it automatically follow the main releases of the npm package?

**Comment by dandv** [comment]
@vvo: that is certainly possible - @acemtp should sign up for http://autopublish.meteor.com, and ping its author (@splendido) for help if needed.

**Pull request merged**
